#! /bin/sh
set -euo pipefail

bold=$(tput bold)
normal=$(tput sgr0)

iter=${iter:-alt5}
YC_BUCKET=${YC_BUCKET:-alt-distr}
FAMILY=${FAMILY:-alt-server-9}
PACKER_CACHE_DIR=${PACKER_CACHE_DIR:-./packer_cache}
target=${target:-alt-server}
arch=${arch:-x86_64}
TARGET_VERSION=${TARGET_VERSION:-9.2}
VM_TYPE=${VM_TYPE:-yandex}
endpoint=${endpoint:-https://storage.yandexcloud.net}

yc_image_name=${target}-${TARGET_VERSION}-${iter}-${arch}
yc_image_name=${yc_image_name//[._]/-}

echo "QCOW2 image: ${VM_TYPE}-${target}-${TARGET_VERSION}-${arch}/${VM_TYPE}-${target}-${TARGET_VERSION}-${arch}"

echo "Name: ${target}-${TARGET_VERSION}-${iter}-${arch}"
echo "URI: ${endpoint}/${YC_BUCKET}/${target}-${TARGET_VERSION}-${iter}-${arch}"
echo "Yandex Cloud S3 Bucket: ${YC_BUCKET}"
echo "Family: ${FAMILY}"
echo "Distributive version: ${TARGET_VERSION}"
echo "Iteration: ${iter}"
echo ""

echo "${bold}Uploading into Yandex Cloud S3 Storage...${normal}"
aws --endpoint-url=${endpoint} s3 cp ${VM_TYPE}-${target}-${TARGET_VERSION}-${arch}/${VM_TYPE}-${target}-${TARGET_VERSION}-${arch} s3://${YC_BUCKET}/${target}-${TARGET_VERSION}-${iter}-${arch}
echo "${bold}Upload complite${normal}"
echo ""

echo "${bold}Creating Yandex Cloud image...${normal}"
yc compute image create --name "${yc_image_name}" --source-uri "${endpoint}/${YC_BUCKET}/${target}-${TARGET_VERSION}-${iter}-${arch}" --family "${FAMILY}"
echo "${bold}Image created:${normal} ${target}-${TARGET_VERSION}-${iter}-${arch}"
