#! /bin/sh
set -euo pipefail

echo "Setting up VirtIOFS kernel module loading on boot"
echo "virtiofs" >> /etc/modules
echo "virtio_console" >> /etc/modules
installkernel $(uname -r)
echo "Setting up VirtIOFS kernel module loading on boot complete"
