#! /bin/sh
set -euo pipefail

echo "Configuring Vagrant user"
alterator-cmdline -d /users/create_account new_name "vagrant" allow_su true auto true passwd_1 "vagrant" passwd_2 "vagrant"
mkdir -p /home/vagrant/.ssh
curl "http://${PACKER_HTTP_ADDR}/pubkeys/vagrant.pub" -o "/home/vagrant/.ssh/authorized_keys"
chown -Rv vagrant:vagrant /home/vagrant
gpasswd -a vagrant wheel
echo "Vagrant user configured"

