#! /bin/sh
set -euo pipefail

echo "Configuring Grub2 for TTY console kernel params"
sed -i "/GRUB_CMDLINE_LINUX_DEFAULT/s/='/='console=ttyS0 /" /etc/sysconfig/grub2
echo "ttyS0" >> /etc/securetty
grub-mkconfig -o /boot/grub/grub.cfg
echo "TTY configured"

