#! /bin/sh
set -euo pipefail

echo "Reseting root password"
sed -E 's/^(root:)[^:]*(.*)$/\1!\2/' -i /etc/shadow
sed -E 's/^([^:]*:)[^:]*(.*)$/\1!\2/' -i /etc/tcb/root/shadow
passwd -l root
echo "Root password reset and locked"
