#! /bin/sh
set -euo pipefail

echo "Configuring cloud-init"
apt-get -y install cloud-init
mkdir -p /usr/lib/python3/site-packages/cloudinit/net
#curl "http://${PACKER_HTTP_ADDR}/scripts/etcnet.py" -o "/usr/lib/python3/site-packages/cloudinit/net/etcnet.py"
#curl "http://${PACKER_HTTP_ADDR}/scripts/altlinux.py" -o "/usr/lib/python3/site-packages/cloudinit/distros/altlinux.py"
systemctl enable cloud-init cloud-init-local
echo "cloud-init configured"

