#! /bin/sh
set -euo pipefail

echo "Configuring APT"

mv "/tmp/.private/root/rc.apt" "/etc/rc.d/scripts/apt-cache-on-tmp"
mv "/tmp/.private/root/rc.local" "/etc/rc.d/rc.local"
mv "/tmp/.private/root/tmp.cache.conf" "/etc/apt/apt.conf.d/tmp.cache.conf"
/etc/rc.d/scripts/apt-cache-on-tmp
apt-get clean
apt-get -qy update
apt-get -qy install apt rpm
apt-get -qy dist-upgrade
apt-get clean

echo "APT configured"

