#! /bin/sh
set -euo pipefail

mv "/tmp/rc.apt" "/etc/rc.d/scripts/apt-cache-on-tmp"
mv "/tmp/rc.local" "/etc/rc.d/rc.local"
mv "/tmp/tmp.cache.conf" "/etc/apt/apt.conf.d/tmp.cache.conf"
/etc/rc.d/scripts/apt-cache-on-tmp
apt-get clean
apt-get -qy update
apt-get -qy install apt rpm
apt-get -qy dist-upgrade
apt-get install -y qemu-guest-agent cloud-init udev-rule-generator-net
systemctl enable qemu-guest-agent
systemctl disable cloud-init
rm -f "/etc/apt/sources.list.d/sources.installer.list"

