#! /bin/sh
set -euo pipefail

echo "Configuring QEMU guest agent"
apt-get install -y qemu-guest-agent
systemctl unmask qemu-guest-agent
systemctl enable qemu-guest-agent
echo "QEMU guest agent configured"

