#! /bin/sh
set -euo pipefail

echo "Setting up new instance service"
apt-repo add 295876
apt-get update
apt-get -y install altlinux-new-instance
systemctl enable altlinux-new-instance
apt-repo rm 295876
echo "Setting up new instance service complete"
