#! /bin/sh
# Setup Ansible prerequisites in order to allow Ansible provisioning
set -euo pipefail

echo "Installing Ansible packages"

apt-get -y install 'python2.7(distutils)'

echo "Ansible prerequisites installed"

