#! /bin/sh
set -euo pipefail

echo "Configuring Grub2 for fixed interface names kernel params"
sed -i "/GRUB_CMDLINE_LINUX_DEFAULT/s/='/='net.ifnames=0 /" /etc/sysconfig/grub2
grub-mkconfig -o /boot/grub/grub.cfg
echo "Fixed interface names configured"

