#! /bin/sh
set -euo pipefail

echo "Reseting root password"
root_pass=$(dd if=/dev/urandom bs=1 count=16 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev)
echo "root:$root_pass" | chpasswd
passwd -l root
echo "Root password reset and locked"
